/**
 * Mock SAM.gov contracts data for testing and initial display.
 * In production, this would be replaced with real SAM.gov API integration.
 */

export const mockContracts = [
  {
    samId: "SAM-2026-001",
    title: "Office Supplies and Equipment",
    description: "Competitive set-aside for small businesses. Supplies include office furniture, computers, and peripherals.",
    simplifiedDescription: "Government needs office supplies and furniture. Easy win for small businesses. No big companies competing.",
    agency: "General Services Administration",
    contractType: "Micro-Purchase",
    simplifiedType: "Quick Win Under $15K",
    value: 12500,
    deadline: new Date("2026-05-15"),
    difficulty: "easy",
    category: "Supplies",
    setAside: "Small Business Set-Aside",
    naicsCode: "453210",
    url: "https://sam.gov/contract/SAM-2026-001",
    minTierRequired: "scout",
  },
  {
    samId: "SAM-2026-002",
    title: "IT Help Desk Support Services",
    description: "Simplified acquisition for IT support services. Includes phone support, ticketing system, and remote assistance.",
    simplifiedDescription: "Government needs IT support staff to answer help desk calls and fix computer problems. Fast-track bid process.",
    agency: "Department of Veterans Affairs",
    contractType: "Simplified Acquisition",
    simplifiedType: "Fast-Track Bid ($15K-$350K)",
    value: 85000,
    deadline: new Date("2026-06-01"),
    difficulty: "moderate",
    category: "Services",
    setAside: "Small Business Set-Aside",
    naicsCode: "541512",
    url: "https://sam.gov/contract/SAM-2026-002",
    minTierRequired: "scout",
  },
  {
    samId: "SAM-2026-003",
    title: "Janitorial and Custodial Services",
    description: "Competitive set-aside for small businesses. Includes daily cleaning, floor maintenance, and waste removal.",
    simplifiedDescription: "Government office buildings need cleaning and maintenance. Steady work, predictable income.",
    agency: "Department of Interior",
    contractType: "Indefinite Delivery/Indefinite Quantity",
    simplifiedType: "Open-Ended Order (Buy As Needed)",
    value: 250000,
    deadline: new Date("2026-05-30"),
    difficulty: "easy",
    category: "Services",
    setAside: "Small Business Set-Aside",
    naicsCode: "561720",
    url: "https://sam.gov/contract/SAM-2026-003",
    minTierRequired: "scout",
  },
  {
    samId: "SAM-2026-004",
    title: "Marketing and Advertising Services",
    description: "Competitive procurement for digital marketing, social media management, and content creation.",
    simplifiedDescription: "Government agencies need help with social media, websites, and advertising. Creative work, good margins.",
    agency: "Department of Commerce",
    contractType: "Fixed-Price Contract",
    simplifiedType: "Flat Fee Deal",
    value: 150000,
    deadline: new Date("2026-06-15"),
    difficulty: "moderate",
    category: "Services",
    setAside: "Women-Owned Small Business",
    naicsCode: "541810",
    url: "https://sam.gov/contract/SAM-2026-004",
    minTierRequired: "operator",
  },
  {
    samId: "SAM-2026-005",
    title: "Construction and Renovation Services",
    description: "Competitive bid for facility renovation including painting, flooring, and minor structural work.",
    simplifiedDescription: "Government building needs renovation. Includes painting, flooring, and repairs. Larger project, higher profit potential.",
    agency: "General Services Administration",
    contractType: "Standard Procurement",
    simplifiedType: "Full Bid Process ($350K+)",
    value: 500000,
    deadline: new Date("2026-07-01"),
    difficulty: "hard",
    category: "Construction",
    setAside: "HUBZone Program",
    naicsCode: "236220",
    url: "https://sam.gov/contract/SAM-2026-005",
    minTierRequired: "contractor",
  },
  {
    samId: "SAM-2026-006",
    title: "Training and Professional Development",
    description: "Competitive set-aside for small businesses to provide employee training in compliance, safety, and leadership.",
    simplifiedDescription: "Government employees need training. You deliver courses. Recurring revenue potential.",
    agency: "Department of Labor",
    contractType: "Simplified Acquisition",
    simplifiedType: "Fast-Track Bid ($15K-$350K)",
    value: 95000,
    deadline: new Date("2026-05-25"),
    difficulty: "moderate",
    category: "Services",
    setAside: "Service-Disabled Veteran-Owned",
    naicsCode: "611430",
    url: "https://sam.gov/contract/SAM-2026-006",
    minTierRequired: "scout",
  },
  {
    samId: "SAM-2026-007",
    title: "Consulting and Strategic Planning",
    description: "Competitive procurement for management consulting, process improvement, and strategic planning services.",
    simplifiedDescription: "Government agencies need consultants to help with strategy and operations. High-value, high-margin work.",
    agency: "Office of Management and Budget",
    contractType: "Cost-Reimbursement",
    simplifiedType: "Pay As You Go (Costs + Fee)",
    value: 350000,
    deadline: new Date("2026-06-20"),
    difficulty: "hard",
    category: "Services",
    setAside: "None",
    naicsCode: "541611",
    url: "https://sam.gov/contract/SAM-2026-007",
    minTierRequired: "contractor",
  },
  {
    samId: "SAM-2026-008",
    title: "Software Development and Maintenance",
    description: "Competitive procurement for custom software development, maintenance, and technical support.",
    simplifiedDescription: "Government needs software built or updated. Tech skills in high demand. Premium pricing.",
    agency: "Department of Defense",
    contractType: "Indefinite Delivery/Indefinite Quantity",
    simplifiedType: "Open-Ended Order (Buy As Needed)",
    value: 1000000,
    deadline: new Date("2026-07-10"),
    difficulty: "hard",
    category: "Technology",
    setAside: "None",
    naicsCode: "541511",
    url: "https://sam.gov/contract/SAM-2026-008",
    minTierRequired: "prime",
  },
  {
    samId: "SAM-2026-009",
    title: "Subcontracting Opportunities",
    description: "Prime contractor seeking subcontractors for various services and supplies. Multiple opportunities available.",
    simplifiedDescription: "Big contractor is looking for small businesses to help. Lower risk than direct government contracts.",
    agency: "Multiple Agencies",
    contractType: "Subcontracting",
    simplifiedType: "Team Up with Big Contractor",
    value: 200000,
    deadline: new Date("2026-05-20"),
    difficulty: "easy",
    category: "Subcontracting",
    setAside: "Small Business Set-Aside",
    naicsCode: "561990",
    url: "https://sam.gov/contract/SAM-2026-009",
    minTierRequired: "scout",
  },
  {
    samId: "SAM-2026-010",
    title: "Cooperative Purchasing Agreement",
    description: "Cooperative purchasing vehicle for office supplies, equipment, and services. Multiple agencies can order.",
    simplifiedDescription: "Get on a government shopping list. Agencies buy from you without competitive bidding. Steady income.",
    agency: "General Services Administration",
    contractType: "GSA Schedule",
    simplifiedType: "Pre-Approved Vendor List",
    value: 750000,
    deadline: new Date("2026-06-10"),
    difficulty: "moderate",
    category: "Supplies",
    setAside: "Small Business Set-Aside",
    naicsCode: "423990",
    url: "https://sam.gov/contract/SAM-2026-010",
    minTierRequired: "operator",
  },
];

export type MockContract = (typeof mockContracts)[0];
